export const STRINGS = {
  TAG_KEYS: {
    MAISON: 'maison',
    TRAVAIL: 'travail',
    SANTE: 'sante',
    ZEN: 'zen',
    PROJETS: 'projets',
    A_TRIER: 'a_trier',
  },
  TAG_LABELS: {
    maison: 'Maison',
    travail: 'Travail',
    sante: 'Sante',
    zen: 'Zen',
    projets: 'Projets',
    a_trier: 'A Trier',
  },
  TAG_EDITOR: {
    title: 'Tags suggeres',
    addPlaceholder: 'Ajouter un tag',
    addButton: 'Ajouter',
  },
  NLU_TRAINING: {
    fr: {
      TASK: [
        'Rappelle moi de payer la facture demain',
        'Preparer le dossier pour lundi',
        'Envoyer un message a Camille ce soir',
      ],
      HABIT: [
        'Je veux mediter chaque matin',
        'Faire une marche tous les jours',
        'Boire de l eau tous les soirs',
      ],
      NOTE: [
        'Idee pour le projet photo',
        'Noter une pensee pour plus tard',
        'Inspiration de la journee',
      ],
    },
    en: {
      TASK: [
        'Remind me to send the invoice tomorrow',
        'Prepare the report for Monday',
        'Call Alex tonight',
      ],
      HABIT: [
        'Meditate every morning',
        'Walk every day',
        'Read each evening',
      ],
      NOTE: [
        'Idea for the new launch',
        'Thought to keep for later',
        'Quick inspiration note',
      ],
    },
    es: {
      TASK: ['Recordarme pagar la factura manana', 'Enviar el correo esta noche', 'Preparar la reunion del lunes'],
      HABIT: ['Meditar cada manana', 'Caminar todos los dias', 'Leer cada noche'],
      NOTE: ['Idea para el proyecto', 'Pensamiento para despues', 'Nota de inspiracion'],
    },
    de: {
      TASK: ['Erinnere mich morgen an die Rechnung', 'Bericht fuer Montag vorbereiten', 'Heute Abend Alex anrufen'],
      HABIT: ['Jeden Morgen meditieren', 'Jeden Tag spazieren', 'Jeden Abend lesen'],
      NOTE: ['Idee fuer das Projekt', 'Gedanke fuer spaeter', 'Kurze Inspirationsnotiz'],
    },
    it: {
      TASK: ['Ricordami di pagare la bolletta domani', 'Preparare il report per lunedi', 'Chiamare Alex stasera'],
      HABIT: ['Meditare ogni mattina', 'Camminare ogni giorno', 'Leggere ogni sera'],
      NOTE: ['Idea per il progetto', 'Pensiero per dopo', 'Nota di ispirazione'],
    },
    ja: {
      TASK: ['明日請求書を払うのを思い出させて', '月曜の資料を準備する', '今夜アレックスに電話する'],
      HABIT: ['毎朝瞑想する', '毎日散歩する', '毎晩読書する'],
      NOTE: ['プロジェクトのアイデア', 'あとで見返すメモ', 'ひらめきメモ'],
    },
    zh: {
      TASK: ['提醒我明天付账单', '准备周一的报告', '今晚给Alex打电话'],
      HABIT: ['每天早上冥想', '每天散步', '每晚阅读'],
      NOTE: ['项目灵感', '留到之后的想法', '快速灵感记录'],
    },
  },
  COMMON: {
    APP_NAME: 'Trankil',
    CANCEL: 'Annuler',
    DELETE: 'Supprimer',
    SAVE: 'Enregistrer',
    REFRESH: 'Rafraichir',
    COPY_JSON: 'Copier JSON',
    EMPTY_DB: 'Base vide pour le moment.',
  },
  CAPTURE: {
    LOCAL_MAX: 'Efficacite Max ! ⚡',
    NOISE_WARNING: "Desole, je n'ai pas bien saisi l'intention ?",
  },
  FLOWER: {
    GROWTH_LABEL: 'Croissance',
    SOBRIETY_SCORE: 'Ton Score de Sobriete',
    DEBUG_AESTHETIC: 'aesthetic_score',
    DEBUG_UTILITY: 'utility_score',
    DEBUG_LOCAL_AFFINITY: 'local_affinity',
    DEBUG_INSECTS: 'insects',
    DEBUG_HERBIER: 'herbier',
    DEBUG_SOBRIETY: 'sobriete',
  },
  GARDEN_RITUALS: {
    VRAC: 'Vrac',
    FOCUS_CIRCLES: 'Focus Circles',
    LIFE_CARD: 'Carte de Vie',
    ACTIONS: 'ACTIONS',
    RITUALS: 'RITUELS',
    REFLECTIONS: 'REFLEXIONS',
    AUDIOS: 'AUDIOS',
    RAW_AUDIO: 'Audio brut',
    ALL_CLEAR: 'Ciel degage, ton esprit est libre.',
    SWARM_WARNING: "Ton Meli-Melo s'encombre. Secoue pour ranger !",
    IN_PROGRESS: 'Meli-Melo en cours',
    EMPTY_DRAFTS: 'Aucun brouillon pour le moment.',
    CALM_EMPTY: 'Tout est calme ici. Profite de cet espace libre.',
    QUICK_EDIT: 'Modification rapide',
    TITLE_PLACEHOLDER: 'Titre',
    CATEGORY_PLACEHOLDER: 'Categorie',
    SHAKE_CONFIRM_TITLE: 'Secouer pour ranger',
    SHAKE_CONFIRM_COST: 'Cout : 1 credit',
    SHAKE_SORT: 'Ranger',
    SHAKE_SORTING: 'Rangement...',
    INSUFFICIENT_CREDITS: 'Petite pause credits',
    INSUFFICIENT_CREDITS_BODY:
      "Tu as besoin d'au moins 1 credit pour ranger le Meli-Melo.",
    DELETE_DRAFT_TITLE: 'Supprimer',
    DELETE_DRAFT_BODY: 'Supprimer cette intention brouillon ?',
    MAGIC_SHAKE_ERROR: 'Le rangement magique a besoin d un souffle',
  },
  REWARDS: {
    CLEAR_DATABASE: 'Vider la base',
    CLEAR_DATABASE_BODY:
      'Cette action supprime toutes les donnees locales SQLite. Continuer ?',
  },
  LOCAL_ECO_LABEL: 'Badge Eco',
  LOCAL_ECO_PRAISE: [
    'Efficacite Max ! ⚡',
    "Ton esprit et l'appli sont en parfaite synchro !",
    'Mode local active: sobre et ultra rapide.',
  ],
  SHARE_MESSAGE:
    "Une fleur de clarté pousse chaque jour. Je cultive mon cap avec Trankil.",
  admin: {
    title: 'Admin Panel',
    kpiMargin: 'Taux de Marges',
    kpiTokens: 'Consommation Tokens',
    kpiAds: 'Efficacite Pub',
    kpiBio: 'Bio-Compatibilite',
    forceMorning: 'Force Morning',
    forceEvening: 'Force Evening',
    spawnFlies: 'Spawn Flies',
    resetCredits: 'Reset Credits',
    spawnDone: '10 mouches debug ajoutees.',
    resetDone: 'Credits remis a zero.',
  },
  HARVEST_SUCCESS: {
    title: 'Floraison complete',
    body: 'Ta fleur rejoint l Herbier des Saisons. Une nouvelle graine prend racine.',
  },
  INSECT_WARNING: {
    lightBuzz: 'Leger bourdonnement autour de la fleur.',
    swarm: "La nuee revient. Un nettoyage doux peut t'aider.",
  },
  AD_REWARDS: {
    REWARD_CLEAN: 'REWARD_CLEAN',
    REWARD_SUN: 'REWARD_SUN',
  },
  BONUS_MESSAGES: {
    utilityCredits: '+2 credits de secours',
    utilityMagicShake: '1 Magic Shake gratuit debloque',
    aestheticFlowerBoost: '+5 Boosts Fleurs',
    aestheticPshitt: '1 Pshitt Spray offert',
    superBonusLocal:
      "Ton esprit est si clair que l'Expert peut se reposer. Voici un cadeau !",
  },
  /* DEPRECATED — nudge disponibilité (voir nettoyage-code-mort.md §5)
  nudges: {
    availabilityTitle: '2 minutes disponibles ?',
    availabilityBody: (title: string) =>
      `On transforme cet instant en victoire douce : "${title}".`,
    availabilityPrimary: 'Je la fais maintenant',
    availabilitySecondary: 'Plus tard',
    availabilityMissingTask: "Aucune micro-action n'est prête pour l'instant.",
    availabilityToastRescue: '+2 credits de secours accordes',
    availabilityToastBoost: '+1 boost fleur accorde',
  },
  */
  ads: {
    cooldownActive: "On laisse respirer l'esprit avant une nouvelle video.",
    cleanNudge: "Besoin d'un coup de main pour nettoyer ?",
    sunNudge: 'Et si on faisait revenir le soleil ?',
    watchAd: 'Voir une video',
    pshittToast: 'Pshitt! Le jardin se nettoie.',
    sunnyToast: 'Le soleil revient. +3 Boosts Fleurs',
    profileAesthetic: "Ta fleur a besoin de lumiere, redonne-lui de l'eclat ?",
    profileUtility: 'Ton reservoir est vide. Un plein rapide pour continuer ?',
    profileBalanced: "Un petit coup d'elan pour garder ton cap ?",
  },
  profiling: {
    debugTitle: 'Bio-Compatibilite',
    localFastLane: 'Mode rapide active: plus de raccourcis, moins de rituels.',
    localBalanced: 'Mode equilibre: rituels et raccourcis alternes.',
  },
  saturation: {
    overloadedToast: "Ton esprit est trop encombre pour ca... Un petit nettoyage ?",
  },
  rituals: {
    eveningPrompt: 'Une pensee pour demain ?',
    chargingPrompt: 'Tu recharges tes batteries... On recharge ton esprit aussi ?',
    nightThoughtPlaceholder: "Depose ici ta derniere pensee pour dormir l'esprit vide",
    nightThoughtVoice: 'Dicter ma pensee',
    starBonusMax: 'Bonus etoile maximum accorde.',
  },
  errors: {
    genericTitle: 'Un ajustement est necessaire',
    // DEPRECATED — nudge disponibilité : availabilityApplyFailed: "Impossible d'appliquer le nudge de disponibilite.",
    bonusApplyFailed: "Impossible d'appliquer le bonus.",
  },
  herbier: {
    screenTitle: "Herbier des Saisons",
    harvestAction: 'Recolter la fleur',
    emptyState: "Ta galerie est vide pour l'instant. Continue, la prochaine fleur arrive.",
    prestigeUnlocked: 'Coeur de Jardin actif: mouches ralenties de 20%.',
    shareButton: 'Partager ma fleur',
    sharing: 'Partage...',
    viralBonusGranted: '+3 Boosts Fleurs et 1 Pshitt Spray accordes.',
  },
} as const;

