/**
 * Point d’entrée **public** des modules `src/api/*` : Firebase, SQLite Trankil v2,
 * sync et utilitaires d’intentions. Préférer cet index aux imports profonds pour
 * limiter le couplage et faciliter les refactors.
 *
 * @packageDocumentation
 */
export {
  AccountLinkingRequiredError,
  ensureAuthenticatedUser,
  isFirebaseUserAnonymous,
} from './accountLinking';
export { getFirebaseApp, getFirestoreDb } from './firebase';
export {
  addRemainingIntents,
  addIaCredits,
  refundIaCredit,
  // DEPRECATED — nudge disponibilité : applyAvailabilityReward,
  applyGrowthDecayIfNeeded,
  deleteTrankilV2IntentionById,
  consumeTrankilV2IntentCredit,
  countOfflineFirstAiPendingNotes,
  getEveningDoneSummaryToday,
  grantViralBonus,
  getLocalEcoScore,
  getTrankilV2UnorganizedCount,
  countTrankilV2RootTodoTasksDueOnLocalDate,
  getFreeCaptureQuotaSnapshot,
  consumeFreeCaptureSuccessOnce,
  FREE_DAILY_CAPTURE_MAX,
  FREE_DAILY_LIST_MAX,
  getListFreeQuotaSnapshot,
  consumeListFreeSuccessOnce,
  getTrankilV2UserStats,
  growthPointsForType,
  initTrankilV2Schema,
  incrementBehaviorScores,
  incrementAdVideosWatched,
  insertTrankilV2Intention,
  listTrankilV2OrganizedIntentions,
  listTrankilV2Intentions,
  listTrankilV2TimelineItemsByDate,
  listTrankilV2MergedTodayTimelineWithLowPressure,
  listTrankilV2UndatedRootTasks,
  listTrankilV2LowPressureRootTasks,
  TIMELINE_PAGE_SIZE,
  bulkTrankilV2TaskChildStatsByParentIds,
  listArchivedIntentions,
  listTrankilV2MeliArchivesIntentions,
  listTrankilV2IsArchivedIntentions,
  mapTrankilIntentionToTimelineItemRow,
  cleanOldArchives,
  listTrankilV2UnorganizedIntentions,
  markTrankilV2IntentionDone,
  toggleIntentionDone,
  archiveIntention,
  listIntentionsForPass3Cleanup,
  insertDailySummary,
  getLatestDailySummaryForDate,
  // DEPRECATED — nudge disponibilité : pickAvailabilityTask,
  setMorningFocusSelection,
  setAdState,
  recordLocalAffinityEvent,
  saveEmergencyLog,
  setDebugSpawnFlies,
  setNotificationsQuietUntil,
  setEveningRitualDateKey,
  updateGrowth,
  updateTrankilV2IntentionOrganization,
  updateTrankilV2IntentionQuick,
  updateTrankilV2IntentionTitle,
  updateTrankilV2IntentionTemporal,
  updateTrankilV2IntentionArchiveState,
  patchMetadata,
  updateTrankilV2IntentionAlarmFields,
  listTrankilV2PendingAlarmIntentions,
  getTrankilV2IntentionById,
  getProjectsAndLists,
  bootstrapTrankilV2Database,
  getLastTrankilV2IntentionRaw,
} from './trankilV2Db';
export type {
  TrankilIntentStatus,
  TrankilIntentType,
  TrankilV2ChildTaskStats,
  TrankilV2IntentionRow,
  TimelinePaging,
  TimelineSqlContext,
  TrankilV2TimelineDateMode,
  TrankilV2TimelineItemRow,
  TrankilV2UserStatsRow,
  Pass3CleanupBucket,
  FreeCaptureQuotaSnapshot,
  ListFreeQuotaSnapshot,
} from './trankilV2Db';
export { getAppPreference, setAppPreference, clearAllAppPreferences } from './localDb';
export { syncNativeRailAlarmsAfterIntentionWrite } from './intentionHardwareSync';
export {
  getOrCreateDeviceId,
} from './syncService';
