export {
  AccountLinkingRequiredError,
  ensureAuthenticatedUser,
  isFirebaseUserAnonymous,
} from './accountLinking';
export { getFirebaseApp, getFirestoreDb } from './firebase';
export {
  addRemainingIntents,
  addIaCredits,
  refundIaCredit,
  applyAvailabilityReward,
  applyGrowthDecayIfNeeded,
  deleteTrankilV2IntentionById,
  consumeTrankilV2IntentCredit,
  getEveningDoneSummaryToday,
  grantViralBonus,
  getLocalEcoScore,
  getTrankilV2UnorganizedCount,
  getTrankilV2UserStats,
  growthPointsForType,
  initTrankilV2Schema,
  incrementBehaviorScores,
  incrementAdVideosWatched,
  insertTrankilV2Intention,
  listTrankilV2OrganizedIntentions,
  listTrankilV2Intentions,
  listTrankilV2TimelineItemsByDate,
  listTrankilV2UndatedRootTasks,
  bulkTrankilV2TaskChildStatsByParentIds,
  listArchivedIntentions,
  listTrankilV2UnorganizedIntentions,
  markTrankilV2IntentionDone,
  pickAvailabilityTask,
  setMorningFocusSelection,
  setAdState,
  recordLocalAffinityEvent,
  saveEmergencyLog,
  setDebugSpawnFlies,
  setNotificationsQuietUntil,
  setEveningRitualDateKey,
  updateGrowth,
  updateTrankilV2IntentionOrganization,
  updateTrankilV2IntentionQuick,
  updateTrankilV2IntentionTemporal,
  updateTrankilV2IntentionArchiveState,
  updateTrankilV2IntentionAlarmFields,
  listTrankilV2PendingAlarmIntentions,
  getTrankilV2IntentionById,
} from './trankilV2Db';
export type {
  TrankilIntentStatus,
  TrankilIntentType,
  TrankilV2ChildTaskStats,
  TrankilV2IntentionRow,
  TrankilV2TimelineDateMode,
  TrankilV2TimelineItemRow,
  TrankilV2UserStatsRow,
} from './trankilV2Db';
export {
  withLocalDatabase,
  applyMelimeloGrouping,
  createIntention,
  insertIntention,
  listCompletedSessionsBetween,
  listIntentionsDescending,
  listRecentCompletedFocusSessions,
  listUnclusteredPendingIntentions,
  listUnsyncedIntentions,
  markIntentionActive,
  markIntentionSynced,
  updateIntention,
} from './localDb';
export type {
  IntentionRow,
  IntentionStatus,
  UserStatusRow,
} from './localDb';
export { getUserStatus, updateUserStatus } from './localDb';
export { syncNativeRailAlarmsAfterIntentionWrite } from './intentionHardwareSync';
export {
  getOrCreateDeviceId,
  startConnectivitySyncListener,
  syncPendingIntentions,
} from './syncService';
